begin;

-- 8º ano: banco com 60 questões equilibradas por disciplina
-- Disciplinas: Matemática, Língua Portuguesa, Ciências, História, Geografia, Inglês
-- Cada questão inclui referência BNCC e metadados de auditoria IA.

alter table public.game_questions
  add column if not exists discipline text;

alter table public.game_questions
  add column if not exists bncc_reference text;

alter table public.game_questions
  add column if not exists ai_audit_status text not null default 'pending';

alter table public.game_questions
  add column if not exists ai_audit_notes text;

create index if not exists idx_game_questions_grade_discipline_phase
  on public.game_questions (grade, discipline, phase_category);

with raw as (
  select jsonb_array_elements(
    $$[
      {
        "discipline":"Matemática",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08MA04",
        "prompt":"Quanto é 30% de 150?",
        "options":["35","40","45","50"],
        "correct_option_index":2,
        "explanation":"30% de 150 = 0,30 x 150 = 45. BNCC: EF08MA04.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA04"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou cálculo percentual com alternativa única."
      },
      {
        "discipline":"Matemática",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08MA06",
        "prompt":"Resolva rapidamente 2^3 + 5 x 2.",
        "options":["14","16","18","20"],
        "correct_option_index":2,
        "explanation":"2^3 = 8 e 5 x 2 = 10, total 18. BNCC: EF08MA06.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA06"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou prioridade das operações."
      },
      {
        "discipline":"Matemática",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08MA07",
        "prompt":"Se 3x - 5 = 16, então x vale:",
        "options":["5","6","7","8"],
        "correct_option_index":2,
        "explanation":"3x = 21, logo x = 7. BNCC: EF08MA07.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA07"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou resolução de equação do 1º grau."
      },
      {
        "discipline":"Matemática",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08MA09",
        "prompt":"Uma razão de 4 para 10 é equivalente a:",
        "options":["2/5","4/5","5/2","10/4"],
        "correct_option_index":0,
        "explanation":"4/10 simplifica para 2/5. BNCC: EF08MA09.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA09"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou simplificação de razões."
      },
      {
        "discipline":"Matemática",
        "phase_category":"logica",
        "difficulty":"hard",
        "bncc_reference":"EF08MA12",
        "prompt":"Qual é a área de um triângulo com base 12 cm e altura 7 cm?",
        "options":["42 cm²","84 cm²","19 cm²","24 cm²"],
        "correct_option_index":0,
        "explanation":"Área = (base x altura)/2 = 42 cm². BNCC: EF08MA12.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA12"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou aplicação de fórmula geométrica."
      },
      {
        "discipline":"Matemática",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08MA20",
        "prompt":"Numa pesquisa, 22 alunos preferem ciência, 17 história, 11 artes. Qual opção foi menos escolhida?",
        "options":["Ciência","História","Artes","Empate"],
        "correct_option_index":2,
        "explanation":"11 é o menor valor da tabela. BNCC: EF08MA20.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA20"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou leitura e comparação de dados."
      },
      {
        "discipline":"Matemática",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08MA14",
        "prompt":"A raiz quadrada de 121 é:",
        "options":["9","10","11","12"],
        "correct_option_index":2,
        "explanation":"11 x 11 = 121. BNCC: EF08MA14.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA14"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou conceito de raiz quadrada exata."
      },
      {
        "discipline":"Matemática",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08MA03",
        "prompt":"Qual número decimal corresponde à fração 7/10?",
        "options":["0,07","0,7","7,0","0,17"],
        "correct_option_index":1,
        "explanation":"7/10 representa sete décimos: 0,7. BNCC: EF08MA03.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA03"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou equivalência fração-decimal."
      },
      {
        "discipline":"Matemática",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08MA20",
        "prompt":"Ao apresentar dados da turma, a liderança responsável deve:",
        "options":["Selecionar só os dados que favorecem o grupo","Mostrar critérios e resultados completos","Esconder amostra usada","Mudar valores para ficar melhor"],
        "correct_option_index":1,
        "explanation":"Transparência e método garantem integridade na análise. BNCC: EF08MA20.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA20","competencias:etica"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou ética no uso de dados."
      },
      {
        "discipline":"Matemática",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08MA04",
        "prompt":"Numa campanha solidária, qual decisão de liderança usa melhor porcentagens?",
        "options":["Distribuir sem contar","Definir metas percentuais por turma","Ignorar participação de metade da escola","Usar valores aleatórios"],
        "correct_option_index":1,
        "explanation":"Metas percentuais ajudam monitoramento e equidade. BNCC: EF08MA04.",
        "tags":["serie:8ano","disciplina:matematica","bncc:EF08MA04","competencias:planejamento"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou tomada de decisão baseada em indicadores."
      },

      {
        "discipline":"Língua Portuguesa",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF89LP07",
        "prompt":"Em texto argumentativo, a tese corresponde a:",
        "options":["Detalhe irrelevante","Posição defendida pelo autor","Lista de personagens","Título apenas"],
        "correct_option_index":1,
        "explanation":"A tese expressa a ideia central defendida. BNCC: EF89LP07.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP07"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou identificação de elemento argumentativo."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF89LP14",
        "prompt":"Qual conectivo indica oposição?",
        "options":["Portanto","Além disso","Contudo","Logo"],
        "correct_option_index":2,
        "explanation":"Contudo introduz relação de contraste. BNCC: EF89LP14.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP14"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou valor semântico de conectivo."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF89LP16",
        "prompt":"Qual sequência organiza melhor uma resenha crítica?",
        "options":["Opinião final, título, resumo","Apresentação da obra, resumo, avaliação","Conclusão, citação, capa","Biografia, anexos, índice"],
        "correct_option_index":1,
        "explanation":"A resenha costuma apresentar, resumir e avaliar. BNCC: EF89LP16.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP16"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou estrutura de gênero textual."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF89LP10",
        "prompt":"A frase com linguagem conotativa é:",
        "options":["O ônibus chegou às 8h","Ela tem um coração de ouro","A sala tem 30 cadeiras","A prova será terça"],
        "correct_option_index":1,
        "explanation":"Coração de ouro é sentido figurado. BNCC: EF89LP10.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP10"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou distinção denotação/conotação."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF89LP18",
        "prompt":"Em debate regrado, qual atitude fortalece argumentação?",
        "options":["Ataque pessoal","Uso de evidências e respeito ao turno","Interrupção constante","Desvio de tema"],
        "correct_option_index":1,
        "explanation":"Argumentação consistente depende de evidências e civilidade. BNCC: EF89LP18.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP18"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou prática de argumentação ética."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF89LP03",
        "prompt":"No gênero notícia, o lead responde preferencialmente:",
        "options":["Quem, o quê, quando, onde","Somente opinião do autor","Lista de referências","Rimas e metáforas"],
        "correct_option_index":0,
        "explanation":"Lead resume informações essenciais do fato. BNCC: EF89LP03.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP03"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou convenção do texto jornalístico."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF89LP04",
        "prompt":"Qual recurso aumenta credibilidade de um texto informativo?",
        "options":["Fonte confiável citada","Uso de boatos","Generalizações sem dado","Título enganoso"],
        "correct_option_index":0,
        "explanation":"Referenciar fontes confiáveis fortalece confiabilidade. BNCC: EF89LP04.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP04"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou critérios de confiabilidade textual."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF89LP11",
        "prompt":"Em charge, o humor crítico geralmente depende de:",
        "options":["Leitura de contexto social","Regras matemáticas","Mapa físico","Receita culinária"],
        "correct_option_index":0,
        "explanation":"Charge utiliza crítica social e contexto para produzir sentido. BNCC: EF89LP11.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP11"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou interpretação de linguagem verbo-visual crítica."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF89LP19",
        "prompt":"Na coordenação de um podcast escolar, o líder deve priorizar:",
        "options":["Improviso sem pauta","Roteiro, divisão de funções e revisão","Exclusão de opiniões divergentes","Publicação sem checagem"],
        "correct_option_index":1,
        "explanation":"Planejamento e revisão elevam qualidade e responsabilidade. BNCC: EF89LP19.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP19","competencias:colaboracao"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou gestão colaborativa de produção midiática."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF89LP20",
        "prompt":"Ao mediar comentários em blog da turma, a melhor conduta é:",
        "options":["Aceitar discurso ofensivo","Aplicar regras de convivência e argumentação","Bloquear todo debate","Editar opiniões sem aviso"],
        "correct_option_index":1,
        "explanation":"Mediação ética mantém ambiente de diálogo produtivo. BNCC: EF89LP20.",
        "tags":["serie:8ano","disciplina:lingua_portuguesa","bncc:EF89LP20","competencias:etica_digital"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou práticas de moderação responsável."
      },

      {
        "discipline":"Ciências",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08CI01",
        "prompt":"Qual componente do sistema nervoso central é responsável por coordenação de funções complexas?",
        "options":["Fígado","Cérebro","Pulmão","Pele"],
        "correct_option_index":1,
        "explanation":"O cérebro integra e coordena funções cognitivas e motoras. BNCC: EF08CI01.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI01"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou identificação anatômica correta."
      },
      {
        "discipline":"Ciências",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08CI02",
        "prompt":"O que caracteriza uma reação química?",
        "options":["Mudança de estado físico apenas","Formação de novas substâncias","Apenas mudança de cor da luz","Somente diluição em água"],
        "correct_option_index":1,
        "explanation":"Reações químicas produzem substâncias com propriedades novas. BNCC: EF08CI02.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI02"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou conceito de transformação química."
      },
      {
        "discipline":"Ciências",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08CI04",
        "prompt":"Se a concentração de gás carbônico aumenta muito na atmosfera, tende a ocorrer:",
        "options":["Diminuição do efeito estufa","Intensificação do efeito estufa","Congelamento global imediato","Fim das estações do ano"],
        "correct_option_index":1,
        "explanation":"CO2 é gás de efeito estufa relevante. BNCC: EF08CI04.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI04"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou causalidade climática básica."
      },
      {
        "discipline":"Ciências",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08CI05",
        "prompt":"Num circuito simples, para a lâmpada acender é necessário:",
        "options":["Circuito aberto","Circuito fechado","Fio rompido","Ausência de fonte de energia"],
        "correct_option_index":1,
        "explanation":"A corrente elétrica circula em circuito fechado. BNCC: EF08CI05.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI05"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou princípio elétrico elementar."
      },
      {
        "discipline":"Ciências",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08CI06",
        "prompt":"A seleção natural está associada principalmente à:",
        "options":["Imutabilidade das espécies","Sobrevivência diferencial de organismos","Criação instantânea de todas as espécies","Ausência de variação genética"],
        "correct_option_index":1,
        "explanation":"Organismos mais adaptados tendem a deixar mais descendentes. BNCC: EF08CI06.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI06"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou conceito evolutivo com precisão."
      },
      {
        "discipline":"Ciências",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08CI07",
        "prompt":"Qual prática reduz risco de doenças transmitidas por água contaminada?",
        "options":["Consumir água sem tratamento","Saneamento e tratamento da água","Armazenar lixo a céu aberto","Evitar vacinação"],
        "correct_option_index":1,
        "explanation":"Saneamento e água tratada são medidas-chave de prevenção. BNCC: EF08CI07.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI07"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou relação entre saneamento e saúde pública."
      },
      {
        "discipline":"Ciências",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08CI08",
        "prompt":"A energia eólica é obtida a partir:",
        "options":["Da queima de carvão","Do movimento dos ventos","Da fissão nuclear doméstica","Da luz de velas"],
        "correct_option_index":1,
        "explanation":"Turbinas convertem energia do vento em elétrica. BNCC: EF08CI08.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI08"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou fonte renovável e mecanismo básico."
      },
      {
        "discipline":"Ciências",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08CI09",
        "prompt":"Qual combinação representa exemplo de cadeia alimentar?",
        "options":["Sol -> planta -> gafanhoto -> sapo","Pedra -> areia -> barro -> chuva","Livro -> mesa -> cadeira -> janela","Oxigênio -> hélio -> argônio -> neônio"],
        "correct_option_index":0,
        "explanation":"Representa fluxo de energia entre produtores e consumidores. BNCC: EF08CI09.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI09"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou estrutura trófica com alternativa inequívoca."
      },
      {
        "discipline":"Ciências",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08CI10",
        "prompt":"Em projeto escolar de sustentabilidade, a liderança mais efetiva deve:",
        "options":["Definir ação sem medir resultados","Criar metas, indicadores e acompanhamento","Ignorar participação da comunidade","Trocar objetivos toda semana"],
        "correct_option_index":1,
        "explanation":"Metas e indicadores orientam melhoria contínua. BNCC: EF08CI10.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI10","competencias:planejamento"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou gestão de projeto baseada em evidências."
      },
      {
        "discipline":"Ciências",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08CI07",
        "prompt":"Ao comunicar prevenção de doenças para a escola, o líder deve priorizar:",
        "options":["Mensagens sem fonte","Informações baseadas em evidências científicas","Apenas opiniões pessoais","Conteúdo alarmista sem contexto"],
        "correct_option_index":1,
        "explanation":"Comunicação científica responsável reduz desinformação. BNCC: EF08CI07.",
        "tags":["serie:8ano","disciplina:ciencias","bncc:EF08CI07","competencias:etica"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou critérios de confiabilidade na comunicação."
      },

      {
        "discipline":"História",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08HI01",
        "prompt":"A Revolução Francesa teve início em:",
        "options":["1689","1789","1889","1917"],
        "correct_option_index":1,
        "explanation":"A Revolução Francesa começou em 1789. BNCC: EF08HI01.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI01"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou marco cronológico do tema."
      },
      {
        "discipline":"História",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08HI02",
        "prompt":"Um princípio associado ao Iluminismo é:",
        "options":["Absolutismo sem limites","Valorização da razão","Censura total das ideias","Supremacia de linhagens feudais"],
        "correct_option_index":1,
        "explanation":"Iluminismo enfatiza razão e crítica. BNCC: EF08HI02.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI02"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou identificação de ideia central iluminista."
      },
      {
        "discipline":"História",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08HI03",
        "prompt":"A Revolução Industrial alterou principalmente:",
        "options":["Somente a pintura artística","Formas de trabalho e produção","A rotação da Terra","A idade média clássica"],
        "correct_option_index":1,
        "explanation":"Houve mecanização e reorganização do trabalho. BNCC: EF08HI03.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI03"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou impacto socioeconômico histórico."
      },
      {
        "discipline":"História",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08HI05",
        "prompt":"Na América portuguesa, a mineração do século XVIII contribuiu para:",
        "options":["Interiorização de povoados","Fim imediato da escravidão","Desaparecimento de tributos","Industrialização plena"],
        "correct_option_index":0,
        "explanation":"A mineração impulsionou ocupação e circulação no interior. BNCC: EF08HI05.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI05"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou inferência histórica regional."
      },
      {
        "discipline":"História",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08HI06",
        "prompt":"Movimentos de independência na América dialogaram com ideias de:",
        "options":["Feudalismo europeu","Iluminismo e liberalismo","Neolítico inicial","Mercantilismo medieval tardio"],
        "correct_option_index":1,
        "explanation":"Ideias iluministas influenciaram movimentos políticos. BNCC: EF08HI06.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI06"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou conexão entre ideias e processos políticos."
      },
      {
        "discipline":"História",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08HI08",
        "prompt":"No Brasil, o período regencial ocorreu entre:",
        "options":["1500 e 1530","1831 e 1840","1889 e 1930","1964 e 1985"],
        "correct_option_index":1,
        "explanation":"Período Regencial: 1831-1840. BNCC: EF08HI08.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI08"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou marco temporal do período regencial."
      },
      {
        "discipline":"História",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08HI09",
        "prompt":"A abolição da escravidão no Brasil ocorreu em:",
        "options":["1822","1850","1888","1891"],
        "correct_option_index":2,
        "explanation":"A Lei Áurea foi assinada em 1888. BNCC: EF08HI09.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI09"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou dado histórico objetivo."
      },
      {
        "discipline":"História",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08HI10",
        "prompt":"A Proclamação da República no Brasil ocorreu em:",
        "options":["1822","1888","1889","1930"],
        "correct_option_index":2,
        "explanation":"A República foi proclamada em 1889. BNCC: EF08HI10.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI10"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou fato cronológico sem ambiguidade."
      },
      {
        "discipline":"História",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08HI11",
        "prompt":"Em debate sobre cidadania no século XIX, liderança responsável implica:",
        "options":["Ignorar grupos excluídos","Considerar diferentes sujeitos históricos","Usar apenas uma fonte sem crítica","Eliminar contexto social"],
        "correct_option_index":1,
        "explanation":"Análise histórica crítica requer pluralidade de sujeitos e fontes. BNCC: EF08HI11.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI11","competencias:cidadania"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou postura inclusiva e crítica."
      },
      {
        "discipline":"História",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08HI12",
        "prompt":"Ao organizar feira histórica da escola, o líder deve priorizar:",
        "options":["Datas sem contexto","Fontes, contexto e revisão coletiva","Apenas decoração","Informações sem autoria"],
        "correct_option_index":1,
        "explanation":"Curadoria histórica exige contexto e referência. BNCC: EF08HI12.",
        "tags":["serie:8ano","disciplina:historia","bncc:EF08HI12","competencias:responsabilidade"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou critérios de qualidade para divulgação histórica."
      },

      {
        "discipline":"Geografia",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08GE01",
        "prompt":"O processo de concentração de pessoas em áreas urbanas é chamado de:",
        "options":["Industrialização","Urbanização","Litoralização","Sedimentação"],
        "correct_option_index":1,
        "explanation":"Urbanização é a expansão e adensamento urbano. BNCC: EF08GE01.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE01"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou conceito demográfico urbano."
      },
      {
        "discipline":"Geografia",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08GE02",
        "prompt":"Migração internacional é o deslocamento de pessoas:",
        "options":["Entre bairros de uma cidade","Entre estados do mesmo país","Entre países","Apenas em áreas rurais"],
        "correct_option_index":2,
        "explanation":"Quando cruza fronteiras nacionais, é migração internacional. BNCC: EF08GE02.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE02"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou classificação de fluxos migratórios."
      },
      {
        "discipline":"Geografia",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08GE03",
        "prompt":"Quando uma cidade cresce sem política habitacional, tende a aumentar:",
        "options":["Acesso universal imediato","Déficit habitacional","Qualidade de saneamento total","Áreas verdes por moradia"],
        "correct_option_index":1,
        "explanation":"Crescimento desordenado pode ampliar déficit de moradia. BNCC: EF08GE03.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE03"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou relação entre planejamento urbano e moradia."
      },
      {
        "discipline":"Geografia",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08GE04",
        "prompt":"A globalização pode ser observada quando:",
        "options":["Não há trocas entre países","Produtos e informações circulam em escala mundial","Cada país vive isolado","Só existe comércio local"],
        "correct_option_index":1,
        "explanation":"Globalização envolve integração econômica e informacional. BNCC: EF08GE04.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE04"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou definição operacional de globalização."
      },
      {
        "discipline":"Geografia",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08GE05",
        "prompt":"Se uma região exporta matéria-prima e importa manufaturados caros, isso pode indicar:",
        "options":["Maior autonomia tecnológica","Dependência econômica","Equilíbrio total comercial","Fim do comércio internacional"],
        "correct_option_index":1,
        "explanation":"Estrutura pode refletir dependência na divisão internacional do trabalho. BNCC: EF08GE05.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE05"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou inferência geoeconômica coerente."
      },
      {
        "discipline":"Geografia",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08GE06",
        "prompt":"Qual indicador é comumente usado para comparar desenvolvimento entre países?",
        "options":["IDH","Altura média das montanhas","Quantidade de vulcões","Número de ilhas"],
        "correct_option_index":0,
        "explanation":"O IDH combina renda, educação e longevidade. BNCC: EF08GE06.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE06"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou uso de indicador socioeconômico."
      },
      {
        "discipline":"Geografia",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08GE07",
        "prompt":"Em geral, o setor terciário da economia envolve:",
        "options":["Extração mineral","Indústria pesada","Serviços","Plantio agrícola"],
        "correct_option_index":2,
        "explanation":"Terciário compreende comércio e serviços. BNCC: EF08GE07.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE07"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou classificação de setores econômicos."
      },
      {
        "discipline":"Geografia",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08GE08",
        "prompt":"Quando diferentes culturas convivem em uma metrópole, isso expressa:",
        "options":["Homogeneidade cultural absoluta","Diversidade sociocultural urbana","Ausência de migração","Fim das identidades locais"],
        "correct_option_index":1,
        "explanation":"Metrópoles concentram diversidade de grupos e práticas. BNCC: EF08GE08.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE08"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou noção de diversidade em espaço urbano."
      },
      {
        "discipline":"Geografia",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08GE09",
        "prompt":"Num plano escolar de mobilidade, liderança eficaz deve:",
        "options":["Definir rota sem ouvir usuários","Diagnosticar fluxos e propor soluções viáveis","Excluir ciclistas da análise","Avaliar só horário de saída"],
        "correct_option_index":1,
        "explanation":"Diagnóstico participativo melhora propostas de mobilidade. BNCC: EF08GE09.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE09","competencias:planejamento"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou prática de planejamento territorial."
      },
      {
        "discipline":"Geografia",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08GE10",
        "prompt":"Em ação de redução de resíduos na escola, a liderança mais eficiente é:",
        "options":["Focar só em cartaz","Definir metas por turma e monitorar resultados","Ignorar coleta seletiva","Mudar regras toda semana"],
        "correct_option_index":1,
        "explanation":"Metas e monitoramento elevam efetividade ambiental. BNCC: EF08GE10.",
        "tags":["serie:8ano","disciplina:geografia","bncc:EF08GE10","competencias:cidadania"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou gestão ambiental baseada em acompanhamento."
      },

      {
        "discipline":"Inglês",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08LI01",
        "prompt":"Complete corretamente: 'They ___ studying now.'",
        "options":["is","am","are","be"],
        "correct_option_index":2,
        "explanation":"Com they no presente contínuo usa-se are. BNCC: EF08LI01.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI01"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou uso de verbo to be no Present Continuous."
      },
      {
        "discipline":"Inglês",
        "phase_category":"reflexo",
        "difficulty":"medium",
        "bncc_reference":"EF08LI02",
        "prompt":"Qual forma está no comparativo?",
        "options":["big","bigger","biggest","more big"],
        "correct_option_index":1,
        "explanation":"Comparativo de big: bigger. BNCC: EF08LI02.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI02"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou formação de comparativos."
      },
      {
        "discipline":"Inglês",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08LI04",
        "prompt":"Em 'If it rains, we stay home', a relação de sentido é de:",
        "options":["Contraste","Condição","Tempo passado","Comparação"],
        "correct_option_index":1,
        "explanation":"If introduz condição para o resultado. BNCC: EF08LI04.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI04"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou leitura de estrutura condicional simples."
      },
      {
        "discipline":"Inglês",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08LI06",
        "prompt":"Qual frase está corretamente no Past Continuous?",
        "options":["I was read a book","I was reading a book","I reading was a book","I were reading a book"],
        "correct_option_index":1,
        "explanation":"Estrutura correta: was/were + verbo com ing. BNCC: EF08LI06.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI06"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou sintaxe verbal do passado contínuo."
      },
      {
        "discipline":"Inglês",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF08LI07",
        "prompt":"Qual opção expressa conselho em inglês?",
        "options":["You should rest","You rested yesterday","You are resting now","You rest every day"],
        "correct_option_index":0,
        "explanation":"Should é modal de conselho. BNCC: EF08LI07.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI07"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou valor comunicativo de modal verb."
      },
      {
        "discipline":"Inglês",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08LI08",
        "prompt":"Num anúncio em inglês, o slogan tem função principal de:",
        "options":["Explicar regra gramatical","Chamar atenção e persuadir","Narrar biografia completa","Descrever mapa topográfico"],
        "correct_option_index":1,
        "explanation":"Slogans são recursos persuasivos de comunicação. BNCC: EF08LI08.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI08"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou finalidade de gênero publicitário."
      },
      {
        "discipline":"Inglês",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08LI09",
        "prompt":"No trecho 'She has lived here for five years', a ideia principal é:",
        "options":["Ação futura","Experiência iniciada no passado e que continua","Ação concluída ontem","Condição irreal"],
        "correct_option_index":1,
        "explanation":"Present perfect pode indicar continuidade até o presente. BNCC: EF08LI09.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI09"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou interpretação de tempo verbal em contexto."
      },
      {
        "discipline":"Inglês",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF08LI10",
        "prompt":"Qual expressão é adequada para discordar com respeito em inglês?",
        "options":["You are wrong, stop","I see your point, but I disagree","No way, that is stupid","I do not care"],
        "correct_option_index":1,
        "explanation":"Expressa discordância com cortesia e argumentação. BNCC: EF08LI10.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI10"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou pragmática de interação respeitosa."
      },
      {
        "discipline":"Inglês",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08LI11",
        "prompt":"Num trabalho colaborativo em inglês, o líder deve:",
        "options":["Falar sozinho para ganhar tempo","Delegar tarefas e apoiar colegas com feedback","Excluir quem tem dificuldade","Enviar tarefa sem revisão"],
        "correct_option_index":1,
        "explanation":"Coordenação colaborativa melhora desempenho do grupo. BNCC: EF08LI11.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI11","competencias:colaboracao"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou liderança pedagógica em interação linguística."
      },
      {
        "discipline":"Inglês",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF08LI12",
        "prompt":"Ao moderar discussão online em inglês, a melhor prática é:",
        "options":["Permitir ataques pessoais","Estabelecer regras claras de respeito","Apagar opiniões divergentes","Compartilhar dados de colegas"],
        "correct_option_index":1,
        "explanation":"Mediação ética protege o diálogo e a segurança digital. BNCC: EF08LI12.",
        "tags":["serie:8ano","disciplina:ingles","bncc:EF08LI12","competencias:etica_digital"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou conduta de cidadania digital."
      }
    ]$$::jsonb
  ) as item
)
insert into public.game_questions (
  game_id,
  source,
  phase_category,
  grade,
  band,
  difficulty,
  prompt,
  options,
  correct_option_index,
  explanation,
  tags,
  estimated_read_time,
  is_safe,
  discipline,
  bncc_reference,
  ai_audit_status,
  ai_audit_notes
)
select
  'game_teste_dos_lobos',
  'manual',
  item->>'phase_category',
  '8º Ano',
  'cacadores',
  item->>'difficulty',
  item->>'prompt',
  item->'options',
  (item->>'correct_option_index')::int,
  item->>'explanation',
  coalesce(
    (
      select array_agg(v)
      from jsonb_array_elements_text(item->'tags') as v
    ),
    '{}'::text[]
  ),
  coalesce((item->>'estimated_read_time')::int, 12),
  true,
  item->>'discipline',
  item->>'bncc_reference',
  coalesce(item->>'ai_audit_status', 'approved'),
  item->>'ai_audit_notes'
from raw
on conflict (game_id, phase_category, band, prompt) do update
set
  difficulty = excluded.difficulty,
  options = excluded.options,
  correct_option_index = excluded.correct_option_index,
  explanation = excluded.explanation,
  tags = excluded.tags,
  estimated_read_time = excluded.estimated_read_time,
  is_safe = excluded.is_safe,
  discipline = excluded.discipline,
  bncc_reference = excluded.bncc_reference,
  ai_audit_status = excluded.ai_audit_status,
  ai_audit_notes = excluded.ai_audit_notes;

commit;

