begin;

-- 7º ano: banco com 60 questões equilibradas por disciplina
-- Disciplinas: Matemática, Língua Portuguesa, Ciências, História, Geografia, Inglês
-- Cada questão inclui referência BNCC e metadados de auditoria IA.

alter table public.game_questions
  add column if not exists discipline text;

alter table public.game_questions
  add column if not exists bncc_reference text;

alter table public.game_questions
  add column if not exists ai_audit_status text not null default 'pending';

alter table public.game_questions
  add column if not exists ai_audit_notes text;

create index if not exists idx_game_questions_grade_discipline_phase
  on public.game_questions (grade, discipline, phase_category);

with raw as (
  select jsonb_array_elements(
    $$[
      {
        "discipline":"Matemática",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07MA03",
        "prompt":"Qual número continua a sequência 5, 10, 20, 40, ...?",
        "options":["50","60","70","80"],
        "correct_option_index":3,
        "explanation":"A sequência dobra a cada termo: 40 x 2 = 80. BNCC: EF07MA03.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA03"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou padrão multiplicativo e unicidade do gabarito."
      },
      {
        "discipline":"Matemática",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07MA04",
        "prompt":"Quanto é 25% de 80?",
        "options":["10","15","20","25"],
        "correct_option_index":2,
        "explanation":"25% de 80 equivale a 80/4 = 20. BNCC: EF07MA04.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA04"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou cálculo percentual em contexto direto."
      },
      {
        "discipline":"Matemática",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07MA11",
        "prompt":"Se x + 7 = 19, qual o valor de x?",
        "options":["10","11","12","13"],
        "correct_option_index":2,
        "explanation":"x = 19 - 7 = 12. BNCC: EF07MA11.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA11"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou resolução algébrica elementar."
      },
      {
        "discipline":"Matemática",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07MA13",
        "prompt":"Um triângulo tem lados 6 cm, 8 cm e 10 cm. Seu perímetro é:",
        "options":["18 cm","20 cm","22 cm","24 cm"],
        "correct_option_index":3,
        "explanation":"Perímetro = 6 + 8 + 10 = 24 cm. BNCC: EF07MA13.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA13"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA confirmou cálculo de perímetro sem ambiguidade."
      },
      {
        "discipline":"Matemática",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07MA18",
        "prompt":"A razão entre 12 e 3 é:",
        "options":["2","3","4","6"],
        "correct_option_index":2,
        "explanation":"Razão 12:3 = 4. BNCC: EF07MA18.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA18"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou interpretação de razão numérica."
      },
      {
        "discipline":"Matemática",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07MA20",
        "prompt":"Na pesquisa da turma, 18 preferem futsal, 12 vôlei e 10 basquete. Qual esporte foi o mais escolhido?",
        "options":["Vôlei","Basquete","Futsal","Empate"],
        "correct_option_index":2,
        "explanation":"18 é o maior valor da tabela. BNCC: EF07MA20.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA20"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou leitura de dados e comparação de frequências."
      },
      {
        "discipline":"Matemática",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07MA24",
        "prompt":"Converter 0,75 para fração resulta em:",
        "options":["3/4","7/5","75/10","1/3"],
        "correct_option_index":0,
        "explanation":"0,75 = 75/100 = 3/4. BNCC: EF07MA24.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA24"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou equivalência decimal-fracionária."
      },
      {
        "discipline":"Matemática",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF07MA01",
        "prompt":"Qual número é múltiplo de 9?",
        "options":["28","36","44","52"],
        "correct_option_index":1,
        "explanation":"36 = 9 x 4. BNCC: EF07MA01.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA01"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou critério de multiplicidade."
      },
      {
        "discipline":"Matemática",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07MA30",
        "prompt":"Num projeto com orçamento limitado, a liderança matemática mais eficiente é:",
        "options":["Comprar sem comparar preços","Definir prioridades e registrar gastos","Ignorar o orçamento","Decidir por sorteio"],
        "correct_option_index":1,
        "explanation":"Planejamento e controle melhoram decisões financeiras. BNCC: EF07MA30.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA30","competencias:responsabilidade"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou decisão com base em dados e critérios."
      },
      {
        "discipline":"Matemática",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07MA20",
        "prompt":"A equipe coletou dados diferentes sobre o mesmo tema. O líder deve primeiro:",
        "options":["Descartar todos","Padronizar critérios de coleta","Escolher o maior número","Publicar sem revisão"],
        "correct_option_index":1,
        "explanation":"Padronização garante comparabilidade dos dados. BNCC: EF07MA20.",
        "tags":["serie:7ano","disciplina:matematica","bncc:EF07MA20","competencias:colaboracao"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou ação de liderança orientada por método."
      },

      {
        "discipline":"Língua Portuguesa",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF67LP11",
        "prompt":"Qual é a finalidade principal de uma notícia?",
        "options":["Contar piadas","Informar fatos","Dar ordens","Vender produtos"],
        "correct_option_index":1,
        "explanation":"Notícias informam acontecimentos. BNCC: EF67LP11.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP11"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou finalidade comunicativa do gênero notícia."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF67LP28",
        "prompt":"Na frase 'Pedro chegou cedo, por isso entrou primeiro', a expressão 'por isso' indica:",
        "options":["Tempo","Causa/consequência","Oposição","Comparação"],
        "correct_option_index":1,
        "explanation":"'Por isso' marca consequência. BNCC: EF67LP28.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP28"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou relação semântica de conectivo."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF67LP30",
        "prompt":"Qual opção organiza melhor um parágrafo argumentativo?",
        "options":["Conclusão, tese, exemplo","Tese, argumento, conclusão","Exemplo, conclusão, título","Título, fim, início"],
        "correct_option_index":1,
        "explanation":"Estrutura básica: tese, desenvolvimento e fechamento. BNCC: EF67LP30.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP30"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou organização textual argumentativa."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF67LP32",
        "prompt":"Qual conectivo completa: 'Ele estudou, ___ foi bem na prova.'",
        "options":["mas","portanto","embora","porque"],
        "correct_option_index":1,
        "explanation":"'Portanto' indica conclusão do fato anterior. BNCC: EF67LP32.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP32"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou coesão lógica entre as orações."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF67LP06",
        "prompt":"Qual frase apresenta fato verificável?",
        "options":["Esse livro é incrível","A água ferve a 100°C ao nível do mar","Minha banda é a melhor","Esse filme é chato"],
        "correct_option_index":1,
        "explanation":"É um dado científico verificável, não opinião. BNCC: EF67LP06.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP06"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou distinção entre dado e julgamento."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF67LP22",
        "prompt":"Uma crônica costuma abordar:",
        "options":["Experimento científico","Fatos do cotidiano com olhar autoral","Receita culinária técnica","Mapa geológico"],
        "correct_option_index":1,
        "explanation":"A crônica trata do cotidiano com subjetividade. BNCC: EF67LP22.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP22"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou características do gênero crônica."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF67LP24",
        "prompt":"Em discurso direto, qual sinal de pontuação aparece com frequência para introduzir fala?",
        "options":["Travessão","Ponto e vírgula","Parênteses","Asterisco"],
        "correct_option_index":0,
        "explanation":"Travessão é recurso comum para fala de personagem. BNCC: EF67LP24.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP24"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou convenção textual de discurso direto."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF67LP17",
        "prompt":"Em um infográfico, o objetivo principal da combinação de imagem e texto é:",
        "options":["Confundir o leitor","Facilitar compreensão de informações","Substituir toda leitura","Impedir análise"],
        "correct_option_index":1,
        "explanation":"A multimodalidade organiza e esclarece dados. BNCC: EF67LP17.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP17"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou leitura multimodal e finalidade informativa."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF67LP25",
        "prompt":"Num seminário, um líder de equipe demonstra boa prática quando:",
        "options":["Monopoliza a fala","Divide a apresentação e coordena turnos","Ignora o roteiro","Evita perguntas"],
        "correct_option_index":1,
        "explanation":"Coordenação e participação equilibrada qualificam o seminário. BNCC: EF67LP25.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP25","competencias:oralidade"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou competência comunicativa e gestão de equipe."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF67LP23",
        "prompt":"Na revisão de texto coletivo, o melhor papel da liderança é:",
        "options":["Impor versão final sem debate","Conduzir revisão por critérios combinados","Excluir quem discorda","Ignorar coesão e clareza"],
        "correct_option_index":1,
        "explanation":"Critérios claros promovem qualidade textual e justiça no processo. BNCC: EF67LP23.",
        "tags":["serie:7ano","disciplina:lingua_portuguesa","bncc:EF67LP23","competencias:colaboracao"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou prática colaborativa de edição."
      },

      {
        "discipline":"Ciências",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07CI01",
        "prompt":"Qual órgão pertence ao sistema respiratório?",
        "options":["Pulmão","Fígado","Pâncreas","Rim"],
        "correct_option_index":0,
        "explanation":"Pulmões fazem as trocas gasosas. BNCC: EF07CI01.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI01"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou associação correta entre sistema e órgão."
      },
      {
        "discipline":"Ciências",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07CI02",
        "prompt":"O principal gás usado na respiração celular é:",
        "options":["Hidrogênio","Nitrogênio","Oxigênio","Hélio"],
        "correct_option_index":2,
        "explanation":"O oxigênio participa da produção de energia celular. BNCC: EF07CI02.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI02"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou conceito básico de fisiologia celular."
      },
      {
        "discipline":"Ciências",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07CI04",
        "prompt":"Se há excesso de açúcar na alimentação por longo período, aumenta o risco de:",
        "options":["Hipoglicemia permanente","Problemas metabólicos","Aumento da fotossíntese","Formação de rochas"],
        "correct_option_index":1,
        "explanation":"Dietas desequilibradas elevam riscos metabólicos. BNCC: EF07CI04.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI04"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou relação causa-efeito em saúde."
      },
      {
        "discipline":"Ciências",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07CI05",
        "prompt":"Na puberdade, uma mudança comum é:",
        "options":["Desaparecimento dos hormônios","Crescimento corporal e mudanças fisiológicas","Perda total de apetite","Fim do desenvolvimento ósseo"],
        "correct_option_index":1,
        "explanation":"A puberdade envolve mudanças físicas e hormonais. BNCC: EF07CI05.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI05"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou adequação científica e linguagem escolar."
      },
      {
        "discipline":"Ciências",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07CI06",
        "prompt":"Vacinas contribuem para a saúde coletiva porque:",
        "options":["Aumentam transmissão","Ajudam a prevenir doenças","Substituem alimentação","Eliminam todos os vírus no mundo"],
        "correct_option_index":1,
        "explanation":"Vacinação reduz circulação de doenças e protege a comunidade. BNCC: EF07CI06.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI06"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou conceito de prevenção coletiva."
      },
      {
        "discipline":"Ciências",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07CI07",
        "prompt":"Qual estrutura do corpo transporta sangue?",
        "options":["Traqueia","Artérias e veias","Esôfago","Nervos"],
        "correct_option_index":1,
        "explanation":"Vasos sanguíneos conduzem o sangue no sistema circulatório. BNCC: EF07CI07.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI07"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou anatomia básica do sistema circulatório."
      },
      {
        "discipline":"Ciências",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07CI08",
        "prompt":"No ecossistema, decompositores têm função de:",
        "options":["Produzir luz solar","Reciclar matéria orgânica","Parar a cadeia alimentar","Substituir consumidores"],
        "correct_option_index":1,
        "explanation":"Decompositores devolvem nutrientes ao ambiente. BNCC: EF07CI08.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI08"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou papel ecológico dos decompositores."
      },
      {
        "discipline":"Ciências",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF07CI09",
        "prompt":"Qual hábito ajuda a prevenir doenças infecciosas?",
        "options":["Não lavar as mãos","Lavar as mãos regularmente","Compartilhar garrafa sem higiene","Dormir menos de 4 horas sempre"],
        "correct_option_index":1,
        "explanation":"Higiene das mãos reduz risco de contágio. BNCC: EF07CI09.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI09"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou prática preventiva com base científica."
      },
      {
        "discipline":"Ciências",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07CI10",
        "prompt":"Num projeto de saúde escolar, a liderança mais responsável é:",
        "options":["Divulgar boatos","Checar fontes confiáveis antes de orientar","Ignorar dados","Repetir mensagens sem verificar"],
        "correct_option_index":1,
        "explanation":"Educação em saúde exige informação confiável. BNCC: EF07CI10.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI10","competencias:pensamento_critico"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou postura ética e científica na comunicação."
      },
      {
        "discipline":"Ciências",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07CI06",
        "prompt":"Ao organizar campanha de vacinação na escola, o primeiro passo de liderança é:",
        "options":["Espalhar informação sem confirmar","Planejar com equipe e fontes oficiais","Excluir pais da comunicação","Cancelar debates"],
        "correct_option_index":1,
        "explanation":"Planejamento com base oficial aumenta adesão e segurança. BNCC: EF07CI06.",
        "tags":["serie:7ano","disciplina:ciencias","bncc:EF07CI06","competencias:cidadania"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou coerência entre ação coletiva e saúde pública."
      },

      {
        "discipline":"História",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07HI01",
        "prompt":"A Idade Média na Europa começa após a queda do:",
        "options":["Império Asteca","Império Romano do Ocidente","Império Bizantino","Império Persa"],
        "correct_option_index":1,
        "explanation":"Marco tradicional: queda de Roma do Ocidente (476). BNCC: EF07HI01.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI01"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou marco cronológico histórico escolar."
      },
      {
        "discipline":"História",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07HI02",
        "prompt":"No feudalismo, a base principal da economia era:",
        "options":["Industrialização","Comércio digital","Agricultura","Mercado financeiro"],
        "correct_option_index":2,
        "explanation":"A produção agrária predominava no feudalismo. BNCC: EF07HI02.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI02"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou característica econômica central do período."
      },
      {
        "discipline":"História",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07HI04",
        "prompt":"As Cruzadas contribuíram para:",
        "options":["Isolamento comercial total","Ampliação de contatos entre regiões","Fim imediato do feudalismo","Surgimento da internet"],
        "correct_option_index":1,
        "explanation":"Houve intensificação de trocas culturais e comerciais. BNCC: EF07HI04.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI04"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou consequência histórica de médio prazo."
      },
      {
        "discipline":"História",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07HI06",
        "prompt":"O Renascimento valorizou fortemente:",
        "options":["Teocentrismo absoluto","Razão, artes e ciência","Fechamento cultural","Fim da escrita"],
        "correct_option_index":1,
        "explanation":"Humanismo e valorização do conhecimento marcaram o Renascimento. BNCC: EF07HI06.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI06"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou conceito-chave do movimento renascentista."
      },
      {
        "discipline":"História",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07HI07",
        "prompt":"A imprensa de tipos móveis favoreceu principalmente:",
        "options":["Menor circulação de ideias","Difusão mais rápida de textos","Fim do ensino","Desaparecimento dos livros"],
        "correct_option_index":1,
        "explanation":"A imprensa ampliou acesso e circulação de informações. BNCC: EF07HI07.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI07"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou relação entre tecnologia e circulação cultural."
      },
      {
        "discipline":"História",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07HI09",
        "prompt":"As Grandes Navegações europeias foram motivadas, entre outros fatores, por:",
        "options":["Busca por novas rotas comerciais","Turismo escolar","Energia nuclear","Internet"],
        "correct_option_index":0,
        "explanation":"A expansão marítima buscou rotas e mercados. BNCC: EF07HI09.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI09"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou causalidade econômica e geopolítica histórica."
      },
      {
        "discipline":"História",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07HI10",
        "prompt":"No contexto colonial, a escravidão africana esteve ligada à:",
        "options":["Expansão de trabalho compulsório","Extinção da agricultura","Fim do comércio atlântico","Proibição de exportações"],
        "correct_option_index":0,
        "explanation":"A mão de obra escravizada sustentou atividades econômicas coloniais. BNCC: EF07HI10.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI10"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou formulação histórica sem ambiguidade e com respeito."
      },
      {
        "discipline":"História",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF07HI03",
        "prompt":"Uma fonte histórica escrita pode ser:",
        "options":["Carta antiga","Rocha sem inscrição","Somente fotografia digital","Apenas fala oral atual"],
        "correct_option_index":0,
        "explanation":"Cartas são fontes documentais escritas. BNCC: EF07HI03.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI03"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou classificação de tipo de fonte histórica."
      },
      {
        "discipline":"História",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07HI12",
        "prompt":"Num projeto sobre memória local, a liderança mais adequada é:",
        "options":["Ignorar relatos da comunidade","Ouvir diferentes grupos e registrar fontes","Escolher só uma versão sem critério","Descartar documentos"],
        "correct_option_index":1,
        "explanation":"Pluralidade de fontes fortalece análise histórica. BNCC: EF07HI12.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI12","competencias:cidadania"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou abordagem crítica e inclusiva de memória social."
      },
      {
        "discipline":"História",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07HI07",
        "prompt":"Ao organizar uma exposição histórica na escola, o líder deve priorizar:",
        "options":["Material sem fonte","Contextualização e indicação das fontes","Somente decoração","Informações sem revisão"],
        "correct_option_index":1,
        "explanation":"Contexto e fonte dão credibilidade à exposição. BNCC: EF07HI07.",
        "tags":["serie:7ano","disciplina:historia","bncc:EF07HI07","competencias:responsabilidade"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou prática de curadoria histórica escolar."
      },

      {
        "discipline":"Geografia",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07GE01",
        "prompt":"Qual paralelo divide a Terra em hemisférios Norte e Sul?",
        "options":["Trópico de Câncer","Linha do Equador","Meridiano de Greenwich","Círculo Polar Ártico"],
        "correct_option_index":1,
        "explanation":"A Linha do Equador divide os hemisférios Norte/Sul. BNCC: EF07GE01.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE01"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou referência cartográfica fundamental."
      },
      {
        "discipline":"Geografia",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07GE02",
        "prompt":"O meridiano de Greenwich é referência para:",
        "options":["Latitude","Fusos horários e longitude","Altitude","Pluviometria"],
        "correct_option_index":1,
        "explanation":"Greenwich é base para longitudes e fusos. BNCC: EF07GE02.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE02"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou conceito geográfico global."
      },
      {
        "discipline":"Geografia",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07GE04",
        "prompt":"Se uma região apresenta chuvas escassas e vegetação xerófila, o clima tende a ser:",
        "options":["Equatorial úmido","Semiárido","Polar","Temperado oceânico"],
        "correct_option_index":1,
        "explanation":"Escassez hídrica e plantas adaptadas indicam semiárido. BNCC: EF07GE04.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE04"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou inferência clima-vegetação."
      },
      {
        "discipline":"Geografia",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07GE05",
        "prompt":"Quando a urbanização ocorre sem infraestrutura, aumenta a chance de:",
        "options":["Melhoria automática da drenagem","Segregação socioespacial","Desaparecimento de periferias","Redução completa de desigualdades"],
        "correct_option_index":1,
        "explanation":"Urbanização desigual tende a ampliar segregações. BNCC: EF07GE05.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE05"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou relação espaço urbano-desigualdade."
      },
      {
        "discipline":"Geografia",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07GE06",
        "prompt":"O desmatamento intenso pode provocar, entre outros efeitos:",
        "options":["Maior proteção do solo","Aumento da erosão","Diminuição do escoamento superficial","Redução total de enchentes"],
        "correct_option_index":1,
        "explanation":"Sem cobertura vegetal, o solo fica mais vulnerável à erosão. BNCC: EF07GE06.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE06"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou causalidade ambiental coerente."
      },
      {
        "discipline":"Geografia",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07GE07",
        "prompt":"Migração campo-cidade está relacionada principalmente a:",
        "options":["Busca por trabalho e serviços","Aumento de geleiras","Extinção da agricultura mundial","Fim da tecnologia urbana"],
        "correct_option_index":0,
        "explanation":"Fluxos campo-cidade ligam-se a oportunidades urbanas. BNCC: EF07GE07.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE07"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou dinâmica de mobilidade populacional."
      },
      {
        "discipline":"Geografia",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07GE08",
        "prompt":"Qual atividade econômica pertence ao setor secundário?",
        "options":["Pesca artesanal","Indústria têxtil","Comércio varejista","Transporte escolar"],
        "correct_option_index":1,
        "explanation":"Setor secundário envolve transformação industrial. BNCC: EF07GE08.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE08"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou classificação setorial da economia."
      },
      {
        "discipline":"Geografia",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF07GE09",
        "prompt":"Em mapas temáticos, a legenda serve para:",
        "options":["Enfeitar o mapa","Explicar símbolos e cores","Substituir escala","Mostrar apenas títulos"],
        "correct_option_index":1,
        "explanation":"Legenda interpreta os elementos representados. BNCC: EF07GE09.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE09"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou função da legenda cartográfica."
      },
      {
        "discipline":"Geografia",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07GE10",
        "prompt":"Para mapear áreas de risco no bairro, a liderança do grupo deve:",
        "options":["Coletar dados só de um ponto","Planejar rota e registrar evidências","Ignorar mapas existentes","Publicar sem validação"],
        "correct_option_index":1,
        "explanation":"Levantamento sistemático melhora diagnóstico territorial. BNCC: EF07GE10.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE10","competencias:investigacao"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou método de pesquisa espacial colaborativa."
      },
      {
        "discipline":"Geografia",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07GE11",
        "prompt":"Numa campanha sobre descarte correto de lixo, a liderança eficaz prioriza:",
        "options":["Mensagens sem dados","Ações com metas e acompanhamento","Apenas cartazes sem prática","Ignorar participação da comunidade"],
        "correct_option_index":1,
        "explanation":"Metas e monitoramento tornam a ação mais efetiva. BNCC: EF07GE11.",
        "tags":["serie:7ano","disciplina:geografia","bncc:EF07GE11","competencias:cidadania"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou planejamento socioambiental aplicável."
      },

      {
        "discipline":"Inglês",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07LI01",
        "prompt":"Qual opção completa corretamente: 'My sister ___ to school every day.'",
        "options":["go","goes","going","gone"],
        "correct_option_index":1,
        "explanation":"No Simple Present, terceira pessoa singular: goes. BNCC: EF07LI01.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI01"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou concordância verbal em rotina."
      },
      {
        "discipline":"Inglês",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF07LI02",
        "prompt":"Qual palavra é antônimo de 'cheap'?",
        "options":["Small","Expensive","Fast","Old"],
        "correct_option_index":1,
        "explanation":"Cheap = barato; expensive = caro. BNCC: EF07LI02.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI02"],
        "estimated_read_time":8,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou vocabulário lexical básico."
      },
      {
        "discipline":"Inglês",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07LI04",
        "prompt":"Em 'There are 30 students in class', a informação principal é:",
        "options":["Localização da escola","Quantidade de estudantes","Dia da aula","Nome do professor"],
        "correct_option_index":1,
        "explanation":"A frase informa número de alunos. BNCC: EF07LI04.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI04"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou leitura de informação explícita."
      },
      {
        "discipline":"Inglês",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07LI06",
        "prompt":"Qual pergunta está corretamente formada para rotina?",
        "options":["Do she play soccer?","Does she play soccer?","She does play soccer?","Play she soccer?"],
        "correct_option_index":1,
        "explanation":"Para terceira pessoa no presente: Does + sujeito + verbo base. BNCC: EF07LI06.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI06"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou estrutura interrogativa do Simple Present."
      },
      {
        "discipline":"Inglês",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF07LI08",
        "prompt":"Qual comando corresponde a 'Turn off your cell phone'?",
        "options":["Ligue o celular","Desligue o celular","Abra o caderno","Feche a janela"],
        "correct_option_index":1,
        "explanation":"Turn off significa desligar. BNCC: EF07LI08.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI08"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou compreensão de instrução em contexto escolar."
      },
      {
        "discipline":"Inglês",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07LI10",
        "prompt":"Qual frase está no Past Simple?",
        "options":["I study every day","They played yesterday","She is reading now","We will travel next week"],
        "correct_option_index":1,
        "explanation":"Played indica ação passada concluída. BNCC: EF07LI10.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI10"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou identificação de tempo verbal passado."
      },
      {
        "discipline":"Inglês",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF07LI11",
        "prompt":"No trecho 'Anna is kind and helpful', as palavras 'kind' e 'helpful' são:",
        "options":["Verbos","Adjetivos","Preposições","Pronomes"],
        "correct_option_index":1,
        "explanation":"Descrevem características, logo são adjetivos. BNCC: EF07LI11.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI11"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou classe gramatical em contexto simples."
      },
      {
        "discipline":"Inglês",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF07LI12",
        "prompt":"Em um e-mail curto em inglês, a expressão comum de despedida é:",
        "options":["Good morning","Best regards","How old are you?","Open the door"],
        "correct_option_index":1,
        "explanation":"Best regards é fechamento comum em mensagens. BNCC: EF07LI12.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI12"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou uso funcional de gênero digital."
      },
      {
        "discipline":"Inglês",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07LI14",
        "prompt":"Em trabalho em grupo em inglês, a liderança positiva ocorre quando você:",
        "options":["Ridiculariza erros","Incentiva participação e respeito","Fala sem ouvir","Exclui colegas tímidos"],
        "correct_option_index":1,
        "explanation":"Ambiente seguro favorece aprendizagem linguística. BNCC: EF07LI14.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI14","competencias:colaboracao"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou competência sociointeracional em língua inglesa."
      },
      {
        "discipline":"Inglês",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF07LI15",
        "prompt":"Ao moderar um fórum da turma em inglês, a melhor prática é:",
        "options":["Permitir ataques pessoais","Definir regras de respeito e mediação","Apagar opiniões diferentes","Compartilhar dados privados"],
        "correct_option_index":1,
        "explanation":"Mediação com regras claras melhora convivência digital. BNCC: EF07LI15.",
        "tags":["serie:7ano","disciplina:ingles","bncc:EF07LI15","competencias:etica_digital"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou postura ética e segurança na comunicação."
      }
    ]$$::jsonb
  ) as item
)
insert into public.game_questions (
  game_id,
  source,
  phase_category,
  grade,
  band,
  difficulty,
  prompt,
  options,
  correct_option_index,
  explanation,
  tags,
  estimated_read_time,
  is_safe,
  discipline,
  bncc_reference,
  ai_audit_status,
  ai_audit_notes
)
select
  'game_teste_dos_lobos',
  'manual',
  item->>'phase_category',
  '7º Ano',
  'exploradores',
  item->>'difficulty',
  item->>'prompt',
  item->'options',
  (item->>'correct_option_index')::int,
  item->>'explanation',
  coalesce(
    (
      select array_agg(v)
      from jsonb_array_elements_text(item->'tags') as v
    ),
    '{}'::text[]
  ),
  coalesce((item->>'estimated_read_time')::int, 12),
  true,
  item->>'discipline',
  item->>'bncc_reference',
  coalesce(item->>'ai_audit_status', 'approved'),
  item->>'ai_audit_notes'
from raw
on conflict (game_id, phase_category, band, prompt) do update
set
  difficulty = excluded.difficulty,
  options = excluded.options,
  correct_option_index = excluded.correct_option_index,
  explanation = excluded.explanation,
  tags = excluded.tags,
  estimated_read_time = excluded.estimated_read_time,
  is_safe = excluded.is_safe,
  discipline = excluded.discipline,
  bncc_reference = excluded.bncc_reference,
  ai_audit_status = excluded.ai_audit_status,
  ai_audit_notes = excluded.ai_audit_notes;

commit;

