begin;

-- 6º ano: banco inicial com 60 questões equilibradas por disciplina
-- Disciplinas: Matemática, Língua Portuguesa, Ciências, História, Geografia, Inglês
-- Cada questão inclui referência BNCC e metadados de auditoria IA.

alter table public.game_questions
  add column if not exists discipline text;

alter table public.game_questions
  add column if not exists bncc_reference text;

alter table public.game_questions
  add column if not exists ai_audit_status text not null default 'pending';

alter table public.game_questions
  add column if not exists ai_audit_notes text;

create index if not exists idx_game_questions_grade_discipline_phase
  on public.game_questions (grade, discipline, phase_category);

with raw as (
  select jsonb_array_elements(
    $$[
      {
        "discipline":"Matemática",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06MA11",
        "prompt":"Qual número completa a sequência 12, 16, 20, 24, ...?",
        "options":["26","27","28","29"],
        "correct_option_index":2,
        "explanation":"A sequência aumenta de 4 em 4. Referência BNCC: EF06MA11.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA11"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou alinhamento com padrão numérico e enunciado objetivo."
      },
      {
        "discipline":"Matemática",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06MA07",
        "prompt":"Quanto é 3/4 de 20?",
        "options":["12","14","15","16"],
        "correct_option_index":2,
        "explanation":"3/4 de 20 = 15. Referência BNCC: EF06MA07.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA07"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou cálculo fracionário e gabarito único."
      },
      {
        "discipline":"Matemática",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06MA01",
        "prompt":"Uma turma fez 5 grupos com 6 alunos cada. Quantos alunos participaram?",
        "options":["11","25","30","56"],
        "correct_option_index":2,
        "explanation":"5 x 6 = 30. Referência BNCC: EF06MA01.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA01"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA confirmou coerência do problema multiplicativo."
      },
      {
        "discipline":"Matemática",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06MA14",
        "prompt":"Um retângulo tem lados 8 cm e 5 cm. Qual é seu perímetro?",
        "options":["13 cm","26 cm","40 cm","16 cm"],
        "correct_option_index":1,
        "explanation":"Perímetro = 2 x (8 + 5) = 26 cm. Referência BNCC: EF06MA14.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA14"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou aplicação de fórmula de perímetro."
      },
      {
        "discipline":"Matemática",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06MA15",
        "prompt":"Qual medida é equivalente a 2,5 metros?",
        "options":["25 cm","250 cm","2500 cm","2 cm"],
        "correct_option_index":1,
        "explanation":"1 m = 100 cm, então 2,5 m = 250 cm. Referência BNCC: EF06MA15.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA15"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA verificou conversão de unidades sem ambiguidade."
      },
      {
        "discipline":"Matemática",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06MA24",
        "prompt":"No gráfico da turma, segunda=6 livros, terça=8, quarta=5. Qual dia teve mais livros lidos?",
        "options":["Segunda","Terça","Quarta","Todos iguais"],
        "correct_option_index":1,
        "explanation":"O maior valor é 8 na terça-feira. Referência BNCC: EF06MA24.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA24"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA aprovou leitura de dados em representação simples."
      },
      {
        "discipline":"Matemática",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06MA03",
        "prompt":"A temperatura era -2°C e subiu 5°C. Qual a nova temperatura?",
        "options":["-7°C","3°C","7°C","-3°C"],
        "correct_option_index":1,
        "explanation":"-2 + 5 = 3°C. Referência BNCC: EF06MA03.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA03"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA confirmou operação com números inteiros contextualizada."
      },
      {
        "discipline":"Matemática",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF06MA06",
        "prompt":"Qual das opções representa um número primo?",
        "options":["9","15","17","21"],
        "correct_option_index":2,
        "explanation":"17 tem apenas dois divisores: 1 e 17. Referência BNCC: EF06MA06.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA06"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou conceito de divisibilidade e gabarito."
      },
      {
        "discipline":"Matemática",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06MA01",
        "prompt":"Em um trabalho de matemática em grupo, a atitude mais eficaz do líder é:",
        "options":["Fazer tudo sozinho","Distribuir tarefas e revisar junto","Escolher sempre o mesmo colega","Ignorar dúvidas"],
        "correct_option_index":1,
        "explanation":"A colaboração melhora o resultado e a aprendizagem. Referência BNCC: EF06MA01.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA01","competencias:colaboracao"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou aderência socioemocional sem perder foco pedagógico."
      },
      {
        "discipline":"Matemática",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06MA31",
        "prompt":"A turma tem R$120 para um projeto e 4 itens essenciais. Qual decisão demonstra liderança responsável?",
        "options":["Gastar tudo no primeiro item","Planejar orçamento por prioridade","Deixar sem registro","Comprar itens aleatórios"],
        "correct_option_index":1,
        "explanation":"Planejamento por prioridade melhora o uso dos recursos. Referência BNCC: EF06MA31.",
        "tags":["serie:6ano","disciplina:matematica","bncc:EF06MA31","competencias:responsabilidade"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou tomada de decisão com raciocínio financeiro básico."
      },

      {
        "discipline":"Língua Portuguesa",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF67LP11",
        "prompt":"Em um aviso escolar com horário e local de reunião, a finalidade principal é:",
        "options":["Narrar uma história","Informar uma orientação","Expressar opinião","Fazer propaganda"],
        "correct_option_index":1,
        "explanation":"Avisos têm função informativa. Referência BNCC: EF67LP11.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP11"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou identificação de finalidade textual."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF67LP28",
        "prompt":"Na frase 'Ana pegou o livro e ela sorriu', 'ela' se refere a:",
        "options":["Livro","Ana","Frase","Sorriu"],
        "correct_option_index":1,
        "explanation":"O pronome retoma 'Ana'. Referência BNCC: EF67LP28.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP28"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou coesão referencial com resposta inequívoca."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF67LP30",
        "prompt":"Qual ordem deixa os fatos mais coerentes? (1) chegou à escola, (2) acordou, (3) entrou na sala.",
        "options":["2,1,3","1,3,2","3,2,1","1,2,3"],
        "correct_option_index":0,
        "explanation":"A sequência lógica é acordar, chegar e entrar na sala. Referência BNCC: EF67LP30.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP30"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA confirmou ordenação temporal do enunciado."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF67LP32",
        "prompt":"Qual conectivo indica contraste?",
        "options":["Portanto","Além disso","Mas","Porque"],
        "correct_option_index":2,
        "explanation":"'Mas' indica oposição/contraste. Referência BNCC: EF67LP32.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP32"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou valor semântico do conectivo."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF67LP06",
        "prompt":"Qual frase apresenta opinião?",
        "options":["A aula começa às 7h","O livro tem 120 páginas","Este filme é emocionante","A prova foi na terça"],
        "correct_option_index":2,
        "explanation":"Opinião expressa julgamento subjetivo. Referência BNCC: EF67LP06.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP06"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou distinção fato/opinião."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF67LP22",
        "prompt":"Uma fábula costuma terminar com:",
        "options":["Tabela de dados","Moral da história","Notícia jornalística","Mapa"],
        "correct_option_index":1,
        "explanation":"Fábulas geralmente trazem ensinamento final. Referência BNCC: EF67LP22.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP22"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA confirmou característica de gênero textual."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF67LP24",
        "prompt":"Na fala direta, o uso de travessão serve para:",
        "options":["Indicar diálogo","Marcar título","Separar sílabas","Indicar plural"],
        "correct_option_index":0,
        "explanation":"Travessão marca a fala de personagens em muitos textos. Referência BNCC: EF67LP24.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP24"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou convenção de pontuação e gênero narrativo."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF67LP17",
        "prompt":"Em uma tirinha, a imagem e a fala juntas ajudam principalmente a:",
        "options":["Diminuir o sentido","Construir humor e sentido","Eliminar o texto","Substituir a leitura"],
        "correct_option_index":1,
        "explanation":"A leitura de linguagem verbal e não verbal é integrada. Referência BNCC: EF67LP17.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP17"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou multimodalidade com alternativa correta única."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF67LP25",
        "prompt":"Num debate escolar, a postura de liderança mais adequada é:",
        "options":["Interromper colegas","Escutar e argumentar com respeito","Desqualificar opiniões","Falar sem ouvir"],
        "correct_option_index":1,
        "explanation":"Debate saudável exige escuta e respeito. Referência BNCC: EF67LP25.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP25","competencias:dialogo"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou competência argumentativa e convivência democrática."
      },
      {
        "discipline":"Língua Portuguesa",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF67LP23",
        "prompt":"Ao revisar um texto coletivo, o líder deve primeiro:",
        "options":["Apagar o texto inteiro","Combinar critérios com o grupo","Ignorar erros","Escolher apenas sua opinião"],
        "correct_option_index":1,
        "explanation":"Critérios combinados favorecem revisão colaborativa. Referência BNCC: EF67LP23.",
        "tags":["serie:6ano","disciplina:lingua_portuguesa","bncc:EF67LP23","competencias:colaboracao"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou alinhamento com produção textual colaborativa."
      },

      {
        "discipline":"Ciências",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06CI01",
        "prompt":"Qual elemento é biótico em um ecossistema?",
        "options":["Água","Pedra","Planta","Luz do sol"],
        "correct_option_index":2,
        "explanation":"Seres vivos são componentes bióticos. Referência BNCC: EF06CI01.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI01"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA confirmou classificação biótico/abiótico."
      },
      {
        "discipline":"Ciências",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06CI02",
        "prompt":"A passagem da água líquida para vapor chama-se:",
        "options":["Fusão","Evaporação","Condensação","Solidificação"],
        "correct_option_index":1,
        "explanation":"Líquido para gasoso é evaporação. Referência BNCC: EF06CI02.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI02"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou mudança de estado físico."
      },
      {
        "discipline":"Ciências",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06CI03",
        "prompt":"Se os insetos diminuem muito, qual grupo tende a ser afetado primeiro em uma cadeia com sapos e cobras?",
        "options":["Sapos","Rochas","Nuvens","Solo"],
        "correct_option_index":0,
        "explanation":"Sapos dependem dos insetos como alimento. Referência BNCC: EF06CI03.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI03"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou relação de dependência em cadeia alimentar."
      },
      {
        "discipline":"Ciências",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06CI06",
        "prompt":"Para separar areia da água, o método mais adequado é:",
        "options":["Destilação simples","Filtração","Cromatografia","Sublimação"],
        "correct_option_index":1,
        "explanation":"A filtração separa sólido insolúvel de líquido. Referência BNCC: EF06CI06.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI06"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou método de separação de misturas."
      },
      {
        "discipline":"Ciências",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06CI08",
        "prompt":"A alternância entre dia e noite ocorre por causa:",
        "options":["Translação da Terra","Rotação da Terra","Fases da Lua","Eclipses"],
        "correct_option_index":1,
        "explanation":"Dia e noite são resultado da rotação terrestre. Referência BNCC: EF06CI08.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI08"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou fenômeno astronômico básico e gabarito."
      },
      {
        "discipline":"Ciências",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06CI04",
        "prompt":"A célula é importante porque:",
        "options":["É apenas um desenho","É a unidade básica dos seres vivos","Existe só em plantas","Substitui órgãos"],
        "correct_option_index":1,
        "explanation":"Todos os seres vivos são formados por células. Referência BNCC: EF06CI04.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI04"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou conceito fundamental de organização da vida."
      },
      {
        "discipline":"Ciências",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06CI07",
        "prompt":"No ciclo da água, a formação de nuvens ocorre principalmente na:",
        "options":["Fusão","Condensação","Sublimação","Combustão"],
        "correct_option_index":1,
        "explanation":"Vapor resfria e condensa, formando nuvens. Referência BNCC: EF06CI07.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI07"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA confirmou etapa do ciclo hidrológico."
      },
      {
        "discipline":"Ciências",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF06CI09",
        "prompt":"Qual fonte de energia é renovável?",
        "options":["Carvão mineral","Petróleo","Solar","Gás natural"],
        "correct_option_index":2,
        "explanation":"Energia solar é renovável. Referência BNCC: EF06CI09.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI09"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou classificação de fontes energéticas."
      },
      {
        "discipline":"Ciências",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06CI10",
        "prompt":"Durante experimento em laboratório escolar, qual atitude demonstra liderança segura?",
        "options":["Ignorar regras","Compartilhar EPIs e orientar colegas","Correr com materiais","Misturar substâncias sem leitura"],
        "correct_option_index":1,
        "explanation":"Segurança coletiva é prioridade em experimentação. Referência BNCC: EF06CI10.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI10","competencias:seguranca"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou conduta segura e colaboração em prática científica."
      },
      {
        "discipline":"Ciências",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06CI05",
        "prompt":"A escola quer reduzir desperdício de água. Qual proposta de liderança é mais eficaz?",
        "options":["Não fazer nada","Criar campanha com metas e monitoramento","Só reclamar","Fechar todos os bebedouros"],
        "correct_option_index":1,
        "explanation":"Campanha com metas favorece mudança sustentável. Referência BNCC: EF06CI05.",
        "tags":["serie:6ano","disciplina:ciencias","bncc:EF06CI05","competencias:sustentabilidade"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou coerência com prática cidadã em ciências."
      },

      {
        "discipline":"História",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06HI01",
        "prompt":"Um objeto antigo, como uma moeda de outra época, pode ser usado como:",
        "options":["Fonte histórica","Somente decoração","Regra gramatical","Mapa climático"],
        "correct_option_index":0,
        "explanation":"Objetos podem ser fontes para estudar o passado. Referência BNCC: EF06HI01.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI01"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou noção de fonte histórica material."
      },
      {
        "discipline":"História",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06HI02",
        "prompt":"Na ordem cronológica, qual vem primeiro?",
        "options":["Idade Média","Idade Antiga","Idade Moderna","Idade Contemporânea"],
        "correct_option_index":1,
        "explanation":"A Idade Antiga antecede as demais listadas. Referência BNCC: EF06HI02.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI02"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou sequência temporal histórica padrão."
      },
      {
        "discipline":"História",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06HI05",
        "prompt":"O desenvolvimento da agricultura favoreceu principalmente:",
        "options":["Nomadismo permanente","Sedentarização","Fim das aldeias","Desaparecimento das trocas"],
        "correct_option_index":1,
        "explanation":"A agricultura permitiu fixação em territórios. Referência BNCC: EF06HI05.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI05"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou relação causa-consequência histórica."
      },
      {
        "discipline":"História",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06HI07",
        "prompt":"Na Mesopotâmia, a escrita foi importante porque:",
        "options":["Acabou com a agricultura","Ajudou no registro administrativo","Substituiu as cidades","Impediu comércio"],
        "correct_option_index":1,
        "explanation":"A escrita apoiou registros, leis e administração. Referência BNCC: EF06HI07.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI07"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou função social da escrita em civilizações antigas."
      },
      {
        "discipline":"História",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06HI09",
        "prompt":"A relação entre o rio Nilo e o Egito Antigo foi marcada por:",
        "options":["Seca total anual","Fertilidade e agricultura","Ausência de povoamento","Somente navegação militar"],
        "correct_option_index":1,
        "explanation":"As cheias do Nilo favoreceram a agricultura egípcia. Referência BNCC: EF06HI09.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI09"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA confirmou vínculo geográfico-histórico essencial."
      },
      {
        "discipline":"História",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06HI11",
        "prompt":"Na Grécia Antiga, o conceito de cidadania estava ligado principalmente à:",
        "options":["Participação política","Uso de moeda única mundial","Navegação oceânica moderna","Industrialização"],
        "correct_option_index":0,
        "explanation":"Cidadania envolvia participação na vida política da polis. Referência BNCC: EF06HI11.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI11"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou conceito de cidadania em contexto antigo."
      },
      {
        "discipline":"História",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06HI13",
        "prompt":"Qual legado romano permanece em muitos países até hoje?",
        "options":["Cuneiforme","Direito romano","Feudos medievais","Pirâmides"],
        "correct_option_index":1,
        "explanation":"O direito romano influenciou sistemas jurídicos posteriores. Referência BNCC: EF06HI13.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI13"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou permanências históricas no tempo presente."
      },
      {
        "discipline":"História",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF06HI03",
        "prompt":"Uma linha do tempo serve para:",
        "options":["Organizar fatos cronologicamente","Desenhar mapas físicos","Classificar espécies","Resolver equações"],
        "correct_option_index":0,
        "explanation":"Linhas do tempo organizam acontecimentos ao longo dos anos. Referência BNCC: EF06HI03.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI03"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou instrumento de organização temporal."
      },
      {
        "discipline":"História",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06HI17",
        "prompt":"Para preservar o patrimônio histórico do bairro, a turma deve primeiro:",
        "options":["Ignorar o tema","Mapear bens e conversar com a comunidade","Pintar sem autorização","Retirar placas antigas"],
        "correct_option_index":1,
        "explanation":"Diagnóstico e diálogo comunitário são base de preservação. Referência BNCC: EF06HI17.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI17","competencias:cidadania"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou ação cidadã vinculada ao patrimônio cultural."
      },
      {
        "discipline":"História",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06HI03",
        "prompt":"Num projeto de linha do tempo coletiva, o líder deve:",
        "options":["Centralizar todas as tarefas","Distribuir pesquisa por períodos e revisar em grupo","Excluir contribuições","Escolher datas aleatórias"],
        "correct_option_index":1,
        "explanation":"Divisão organizada melhora qualidade histórica do trabalho. Referência BNCC: EF06HI03.",
        "tags":["serie:6ano","disciplina:historia","bncc:EF06HI03","competencias:colaboracao"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou planejamento colaborativo com foco histórico."
      },

      {
        "discipline":"Geografia",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06GE01",
        "prompt":"Em um mapa convencional, o Norte costuma ficar:",
        "options":["Na parte superior","Na parte inferior","À esquerda","No centro"],
        "correct_option_index":0,
        "explanation":"Convencionalmente, o norte está no topo do mapa. Referência BNCC: EF06GE01.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE01"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou noção cartográfica básica."
      },
      {
        "discipline":"Geografia",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06GE03",
        "prompt":"Uma escala 1:1000 significa que 1 cm no mapa equivale a:",
        "options":["10 m no real","100 m no real","1 km no real","1 m no real"],
        "correct_option_index":0,
        "explanation":"1 cm x 1000 = 1000 cm = 10 m. Referência BNCC: EF06GE03.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE03"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou interpretação de escala com cálculo correto."
      },
      {
        "discipline":"Geografia",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06GE04",
        "prompt":"Qual opção representa clima e não tempo atmosférico?",
        "options":["Choveu hoje cedo","Está ventando agora","Média anual de chuvas da região","Fez frio pela manhã"],
        "correct_option_index":2,
        "explanation":"Clima refere-se a padrões de longo prazo. Referência BNCC: EF06GE04.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE04"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou distinção entre tempo e clima."
      },
      {
        "discipline":"Geografia",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06GE05",
        "prompt":"Quando uma área perde cobertura vegetal perto de rios, aumenta o risco de:",
        "options":["Assoreamento","Formação de geleiras","Aumento de salinidade oceânica","Terremoto tectônico"],
        "correct_option_index":0,
        "explanation":"Sem vegetação, há maior erosão e assoreamento. Referência BNCC: EF06GE05.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE05"],
        "estimated_read_time":12,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou relação entre uso do solo e impactos ambientais."
      },
      {
        "discipline":"Geografia",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06GE06",
        "prompt":"O crescimento rápido e sem planejamento de uma cidade pode gerar:",
        "options":["Mais áreas verdes automaticamente","Problemas de mobilidade e saneamento","Redução total da produção de lixo","Fim de enchentes"],
        "correct_option_index":1,
        "explanation":"Urbanização sem planejamento costuma agravar infraestrutura. Referência BNCC: EF06GE06.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE06"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA confirmou causalidade socioespacial no enunciado."
      },
      {
        "discipline":"Geografia",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06GE07",
        "prompt":"Qual bioma é típico da região Nordeste e tem vegetação adaptada à seca?",
        "options":["Amazônia","Caatinga","Pampa","Pantanal"],
        "correct_option_index":1,
        "explanation":"A Caatinga é adaptada ao clima semiárido. Referência BNCC: EF06GE07.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE07"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou associação correta entre bioma e região."
      },
      {
        "discipline":"Geografia",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06GE08",
        "prompt":"Quando pessoas mudam de uma região do país para outra, isso é:",
        "options":["Migração interna","Imigração internacional","Turismo eventual","Navegação costeira"],
        "correct_option_index":0,
        "explanation":"Deslocamento dentro do mesmo país é migração interna. Referência BNCC: EF06GE08.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE08"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou conceito de mobilidade populacional."
      },
      {
        "discipline":"Geografia",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF06GE09",
        "prompt":"A atividade de cultivar alimentos no campo pertence ao setor:",
        "options":["Primário","Secundário","Terciário","Quaternário"],
        "correct_option_index":0,
        "explanation":"Agricultura integra o setor primário da economia. Referência BNCC: EF06GE09.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE09"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou classificação setorial da economia."
      },
      {
        "discipline":"Geografia",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06GE10",
        "prompt":"Em um mapeamento do bairro para identificar problemas, a liderança eficaz deve:",
        "options":["Ouvir só uma rua","Coletar dados de diferentes pontos","Inventar informações","Evitar participação da turma"],
        "correct_option_index":1,
        "explanation":"Amostragem diversificada melhora o diagnóstico territorial. Referência BNCC: EF06GE10.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE10","competencias:investigacao"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou estratégia colaborativa de levantamento territorial."
      },
      {
        "discipline":"Geografia",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06GE11",
        "prompt":"Para reduzir risco de enchente perto da escola, a ação mais adequada é:",
        "options":["Jogar lixo nos bueiros","Organizar mutirão de limpeza e prevenção","Canalizar sem estudo","Ignorar período de chuvas"],
        "correct_option_index":1,
        "explanation":"Prevenção e manutenção urbana diminuem riscos. Referência BNCC: EF06GE11.",
        "tags":["serie:6ano","disciplina:geografia","bncc:EF06GE11","competencias:cidadania"],
        "estimated_read_time":14,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou pertinência de ação comunitária preventiva."
      },

      {
        "discipline":"Inglês",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06LI01",
        "prompt":"Qual expressão em inglês é usada para cumprimentar pela manhã?",
        "options":["Good night","Good morning","Good bye","See you"],
        "correct_option_index":1,
        "explanation":"'Good morning' é cumprimento matinal. Referência BNCC: EF06LI01.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI01"],
        "estimated_read_time":8,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou vocabulário básico de interação."
      },
      {
        "discipline":"Inglês",
        "phase_category":"reflexo",
        "difficulty":"easy",
        "bncc_reference":"EF06LI03",
        "prompt":"Qual palavra é cognata de 'animal' em português?",
        "options":["Table","Animal","Window","Chair"],
        "correct_option_index":1,
        "explanation":"'Animal' mantém forma e sentido próximos. Referência BNCC: EF06LI03.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI03"],
        "estimated_read_time":8,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou reconhecimento de cognato transparente."
      },
      {
        "discipline":"Inglês",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06LI05",
        "prompt":"No horário 'Class starts at 7:30', a aula começa às:",
        "options":["6:30","7:30","8:30","7:00"],
        "correct_option_index":1,
        "explanation":"A informação explícita indica 7:30. Referência BNCC: EF06LI05.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI05"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou leitura de informação literal em inglês."
      },
      {
        "discipline":"Inglês",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06LI07",
        "prompt":"Complete: '___ is my friend.'",
        "options":["He","His","Himself","Hers"],
        "correct_option_index":0,
        "explanation":"Pronome sujeito adequado é 'He'. Referência BNCC: EF06LI07.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI07"],
        "estimated_read_time":9,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou escolha gramatical de pronome pessoal."
      },
      {
        "discipline":"Inglês",
        "phase_category":"logica",
        "difficulty":"medium",
        "bncc_reference":"EF06LI09",
        "prompt":"Qual comando em sala de aula significa 'Abram o livro'?",
        "options":["Close the door","Open your book","Write your name","Stand up"],
        "correct_option_index":1,
        "explanation":"'Open your book' corresponde ao comando pedido. Referência BNCC: EF06LI09.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI09"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou compreensão de instruções escolares."
      },
      {
        "discipline":"Inglês",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06LI11",
        "prompt":"Qual frase está no Simple Present para rotina?",
        "options":["I am playing now","She studies every day","We were happy yesterday","They will travel tomorrow"],
        "correct_option_index":1,
        "explanation":"'She studies every day' descreve hábito. Referência BNCC: EF06LI11.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI11"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou uso funcional de tempo verbal em contexto."
      },
      {
        "discipline":"Inglês",
        "phase_category":"conhecimento",
        "difficulty":"medium",
        "bncc_reference":"EF06LI13",
        "prompt":"Qual conjunto contém alimentos saudáveis em inglês?",
        "options":["Chips and soda","Apple and carrot","Candy and chocolate","Burger and fries"],
        "correct_option_index":1,
        "explanation":"Apple e carrot são alimentos saudáveis. Referência BNCC: EF06LI13.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI13"],
        "estimated_read_time":10,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou vocabulário temático com contexto cotidiano."
      },
      {
        "discipline":"Inglês",
        "phase_category":"conhecimento",
        "difficulty":"easy",
        "bncc_reference":"EF06LI15",
        "prompt":"No texto curto 'Tom is at school. He likes math.', o assunto principal é:",
        "options":["O transporte de Tom","A rotina escolar e gosto de Tom","Uma viagem internacional","Uma receita de bolo"],
        "correct_option_index":1,
        "explanation":"O texto fala da escola e preferência de Tom. Referência BNCC: EF06LI15.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI15"],
        "estimated_read_time":11,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou identificação de ideia principal em texto curto."
      },
      {
        "discipline":"Inglês",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06LI17",
        "prompt":"Em atividade em dupla em inglês, a liderança colaborativa é melhor quando você:",
        "options":["Fala sozinho o tempo todo","Escuta o colega e divide falas","Corrige com ironia","Recusa participar"],
        "correct_option_index":1,
        "explanation":"Interação respeitosa desenvolve comunicação real. Referência BNCC: EF06LI17.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI17","competencias:colaboracao"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA auditou prática de interação oral colaborativa."
      },
      {
        "discipline":"Inglês",
        "phase_category":"lideranca",
        "difficulty":"medium",
        "bncc_reference":"EF06LI18",
        "prompt":"Ao enviar mensagem em inglês no fórum da turma, a atitude mais adequada é:",
        "options":["Usar ofensas","Escrever com respeito e clareza","Copiar sem citar fonte","Publicar dados pessoais de colegas"],
        "correct_option_index":1,
        "explanation":"Netiqueta envolve respeito e segurança digital. Referência BNCC: EF06LI18.",
        "tags":["serie:6ano","disciplina:ingles","bncc:EF06LI18","competencias:etica_digital"],
        "estimated_read_time":13,
        "ai_audit_status":"approved",
        "ai_audit_notes":"IA validou conduta ética na comunicação digital."
      }
    ]$$::jsonb
  ) as item
)
insert into public.game_questions (
  game_id,
  source,
  phase_category,
  grade,
  band,
  difficulty,
  prompt,
  options,
  correct_option_index,
  explanation,
  tags,
  estimated_read_time,
  is_safe,
  discipline,
  bncc_reference,
  ai_audit_status,
  ai_audit_notes
)
select
  'game_teste_dos_lobos',
  'manual',
  item->>'phase_category',
  '6º Ano',
  'exploradores',
  item->>'difficulty',
  item->>'prompt',
  item->'options',
  (item->>'correct_option_index')::int,
  item->>'explanation',
  coalesce(
    (
      select array_agg(v)
      from jsonb_array_elements_text(item->'tags') as v
    ),
    '{}'::text[]
  ),
  coalesce((item->>'estimated_read_time')::int, 12),
  true,
  item->>'discipline',
  item->>'bncc_reference',
  coalesce(item->>'ai_audit_status', 'approved'),
  item->>'ai_audit_notes'
from raw
on conflict (game_id, phase_category, band, prompt) do update
set
  difficulty = excluded.difficulty,
  options = excluded.options,
  correct_option_index = excluded.correct_option_index,
  explanation = excluded.explanation,
  tags = excluded.tags,
  estimated_read_time = excluded.estimated_read_time,
  is_safe = excluded.is_safe,
  discipline = excluded.discipline,
  bncc_reference = excluded.bncc_reference,
  ai_audit_status = excluded.ai_audit_status,
  ai_audit_notes = excluded.ai_audit_notes;

commit;

